# KNN Algorithm in Supervised Machine Learning
## KNeighboursClassifier of sklearn library for this one

In [4]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [6]:
# data collection and splitting the data
x = np.array([
    [1,3500],
    [2,3200],
    [3,3000],
    [4,2500],
    [5,2300],
    [6,2000],
    [7,2200],
    [2,3700]
])
y=['Unfit','Unfit','Unfit','Fit','Fit','Fit','Fit','Unfit']

In [7]:
# create the model
model=KNeighborsClassifier(n_neighbors=3)

In [8]:
# Train the model
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [9]:
#predict
new_person=[[4.5,2000]]  #4.5 hrs exercise, 20000 calories
pred = model.predict(new_person)
print("Predicted Result is:\t", pred[0])

Predicted Result is:	 Fit

In [12]:
#prediction from taking input from user
exercise_hours=float(input('Enter Number of Exercise Hours'))
cal_intake=float(input('Enter number of calories consumed'))
pred_fu=model.predict([[exercise_hours,cal_intake]])
print(f'If exercise done for {exercise_hours} hours, the calories intake for the day is {cal_intake}, you are likely {pred_fu}')

Enter Number of Exercise Hours 2
Enter number of calories consumed 3000

If exercise done for 2.0 hours, the calories intake for the day is 3000.0, you are likely ['Unfit']

# Exercise 2

In [13]:
import pandas as pd

In [25]:
df = pd.read_csv('fruit_data.csv')  # reload the original file
df

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange
4     180   7.5       ?

In [29]:
#split the data
x = df[['Weight','Size']]
y = df['Fruit']

In [30]:
# Model creation
model=KNeighborsClassifier(n_neighbors=3)

In [31]:
#train the model
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
our_fruit=pd.DataFrame([[fruit_weight,fruit_size]],columns=['Weight','Size'])

In [36]:
fruit_weight=float(input('Enter your fruit weight in g'))
fruit_size = float(input('Enter your size in cm'))
our_fruit=pd.DataFrame([[fruit_weight,fruit_size]],columns=['Weight','Size'])
pred_fruit = model.predict(our_fruit)
print(f'Fruit weight is {fruit_weight}, and the size is {fruit_size}, the fruit is {pred_fruit[0]}')

Enter your fruit weight in g 4
Enter your size in cm 100

Fruit weight is 4.0, and the size is 100.0, the fruit is Apple

In [39]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [51]:
#1
data=pd.read_csv('student_grade.csv')
data

   Hours_Studied  Assignments_Completed Grade
0            1.5                      1     C
1            2.0                      2     C
2            3.0                      3     B
3            4.0                      4     B
4            5.0                      5     A
5            6.0                      6     A

In [50]:
#2
x=data[['Hours_Studied','Assignments_Completed']]
y=data['Grade']

#3
model=KNeighborsClassifier(n_neighbors=3)

#4
model.fit(x,y)

#5
hr_study=int(input('Enter duration of study in hour:\t'))
asg_compl=int(input('Enter amount of assignment completed:\t'))  
our_student=pd.DataFrame([[hr_study,asg_compl]],columns=['Hours_Studied','Assignments_Completed'])
pred_grade=model.predict(our_student)
print(f'If the student study for {hr_study} hours, and completed {asg_compl} assignments, they will likely be getting {pred_grade[0]}')

Enter duration of study in hour:	 7
Enter amount of assignment completed:	 9

If the student study for 7 hours, and completed 9 assignments, they will likely be getting A