# LogisticReg

In [2]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [3]:
#1: collecting the data
df=pd.read_csv('pass_fail.csv')
df.head(2)

   Hours Result
0      1   Fail
1      2   Fail

In [4]:
#2. splitting the data
Hours_study=df[['Hours']]
Exam_result=df['Result']

In [6]:
#3. model_creation
model = LogisticRegression()

In [7]:
#4. train the model
model.fit(Hours_study,Exam_result)
print('Trained successfully!')

Trained successfully!

In [8]:
pred_35=model.predict([[3.5]])
print('Predicted result for 3.5 hours:',pred_35[0])

Predicted result for 3.5 hours: Pass

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [15]:
est_hour=float(input('Enter new hour:'))
pred_result=model.predict([[est_hour]])
print(f'If you study {est_hour}, then you will be {pred_result[0]}')

Enter new hour: 7

If you study 7.0, then you will be Pass

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

## Exercise 2

In [21]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [22]:
#1: collecting the data
df=pd.read_csv('customer_purchase.csv')
df.head(2)

   Age  Salary Purchased
0   22   25000        No
1   25   30000        No

In [23]:
#2. splitting the data
le=LabelEncoder()
df['Purchased'] = le.fit_transform(df['Purchased'])
x=df[['Age','Salary']]
y=df['Purchased']

In [24]:
df

   Age  Salary  Purchased
0   22   25000          0
1   25   30000          0
2   30   40000          1
3   35   50000          1
4   40   60000          1

In [25]:
#3. model_creation
model = LogisticRegression()

In [26]:
#4. train the model
model.fit(x,y)
print('Trained successfully!')

Trained successfully!

In [29]:
#5. Prediction

new_cust = [[28,35000]]
prediction = model.predict(new_cust)
print(f'Predicted Result(1=Yes, 0=No): {prediction [0]}')

Predicted Result(1=Yes, 0=No): 1

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [31]:
#5. Prediction

new_cust_age=int(input('Enter age:\t'))
new_cust_salary=int(input('Enter salary:\t'))
new_customer=[[new_cust_age,new_cust_salary]]
prediction=model.predict(new_customer)
if (prediction):
    print('Likely purchased')
else:
    print('Likely not purchased')

Enter age:	 56
Enter salary:	 45550

Likely purchased

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

# Exercise 3
# Logistic Regression — Spam/NotSpam
## Download spam_data.csv from https://www.kaggle.com/
## Load the Data
## Do the data cleaning and labeling (if required)
## Use Logistic Regression Algorithm to trained the Model
## Predict Result if the email is spam or not spam

In [46]:
# import the required libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [79]:
#1: collecting the data
df=pd.read_csv('spam_dataset.csv')
df

                                       message_content  is_spam
0    Hello Lonnie,\n\nJust wanted to touch base reg...        0
1    Congratulations, you've won a prize! Call us n...        1
2    You have been pre-approved for a credit card w...        1
3    Limited time offer, act now! Only a few spots ...        1
4    Your loan has been approved! Transfer funds to...        1
..                                                 ...      ...
995  Hello Virginia,\n\nIt was great to catch up wi...        0
996  Final notice: Claim your inheritance from a di...        1
997  Hot singles in your area want to chat! Contact...        1
998  Your loan has been approved! Transfer funds to...        1
999  Dear Brian,\n\nI wanted to let you know about ...        0

[1000 rows x 2 columns]

In [60]:
#2. splitting the data
cv=CountVectorizer()
x = df['message_content']
x_cv=cv.fit_transform(x)
y=df['is_spam']

In [61]:
#3. model_creation
model = LogisticRegression()

In [62]:
#4. train the model
model.fit(x_cv,y)
print('Trained successfully!')

Trained successfully!

In [68]:
#5. Prediction
sample = ["You have been selected to receive a special offer. Act fast!","Hi Alexandra,"]
prediction = model.predict(cv.transform(sample))
print(prediction)

[1 1]

## Another set of answer

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
df_spam_email=pd.read_csv('spam_dataset.csv')
df_spam_email.head(2)

xSpam = df_spam_email['message_content']
ySpam = df_spam_email['is_spam']
 
# Split the data (e.g., 80% for training, 20% for testing)
X_train_text, X_test_text, y_train, y_test = train_test_split(
    xSpam, 
    ySpam, 
    test_size=0.2, 
    random_state=42
)
print("Training samples:", len(X_train_text))
print("Testing samples:", len(X_test_text))
 
vectorizer = CountVectorizer()
X_train_numeric = vectorizer.fit_transform(X_train_text)
X_test_numeric = vectorizer.transform(X_test_text)
 
model_spam_email = LogisticRegression() 
model_spam_email.fit(X_train_numeric, y_train)

Training samples: 800
Testing samples: 200

LogisticRegression()

In [81]:
sample_text = ["You have been selected to receive a special offer. Act fast!","Hello Virginia, It was great to catch up with you"]
prediction = model.predict(cv.transform(sample_text))
print(prediction)

[1 1]