**Mini Project**
Airline Tweet Sentiment Classifier using Natural Language Processing**
---
**Notes:**
Use sample dataset:
https://github.com/salman1256/aimltraining/blob/main/Day-30/airline_tweets_sample.csv

---
# Steps:
1. Import libraries  
2. Load and explore dataset  
3. Clean and preprocess the text  
4. Convert text to numerical vectors (TF-IDF)  
5. Split into train and test sets  
6. Train a Logistic Regression model  
7. Evaluate accuracy and classification report  
8. Predict sentiment for new example tweets

In [227]:
# Step 1 a: Import Required Libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import re
import nltk
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [228]:
# Step 1 b: Download nltk required thing like stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Faridah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Faridah\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Faridah\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Faridah\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Faridah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [229]:
#Step 2 a: Load DataSet
df = pd.read_csv("airline_tweets_sample.csv")

In [230]:
#Step 2 : Check Data set  at least top 5 values
df.head()

                                                text sentiment
0  @United flight was delayed for 3 hours, worst ...  negative
1  Loved the service on @Delta, crew was super fr...  positive
2  @AmericanAir lost my luggage again, so disappo...  negative
3  Smooth boarding and on-time arrival. Great job...  positive
4  The seats were uncomfortable but staff was polite   neutral

In [231]:
# Step 3:
#Text Cleaning and Preprocessing
# For each tweet do:
# a. Convert to lowercase
# b. Remove URLs
# c. Remove special characters and numbers
# d. Remove stopwords (common words like *the, is, and* etc.)
# e. Apply **stemming** (reduce words to their root form)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    words = text.split()
    words = [word for word in words if word not in stopwords.words('english')]
    words = [stemmer.stem(word) for word in words]
    text = ' '.join(words)
    return text

df['clean_tweet']=df['text'].apply(clean_text)
df

,text,sentiment,clean_tweet
0,"@United flight was delayed for 3 hours, worst ...",negative,unit flight delay hour worst experi ever
1,"Loved the service on @Delta, crew was super fr...",positive,love servic delta crew super friendli
2,"@AmericanAir lost my luggage again, so disappo...",negative,americanair lost luggag disappoint
3,Smooth boarding and on-time arrival. Great job...,positive,smooth board ontim arriv great job southwestair
4,The seats were uncomfortable but staff was polite,neutral,seat uncomfort staff polit
5,"@JetBlue flight attendants were rude, not flyi...",negative,jetblu flight attend rude fli
6,"Got a free upgrade to business class, thank yo...",positive,got free upgrad busi class thank unit
7,"Average flight, nothing special to mention",neutral,averag flight noth special mention
8,@DeltaAirLines provided excellent support with...,positive,deltaairlin provid excel support book
9,The in-flight entertainment was not working,negative,inflight entertain work
10,Snacks were good but the legroom was terrible,negative,snack good legroom terribl
11,@SouthwestAir always makes flying fun!,positive,southwestair alway make fli fun
12,Check-in process was quick and easy,positive,checkin process quick easi
13,Customer service kept me on hold for 40 minutes,negative,custom servic kept hold minut
14,"Flight was okay, staff were fine, nothing to c...",neutral,flight okay staff fine noth complain
15,"Super smooth landing, kudos to the pilot",positive,super smooth land kudo pilot
16,I missed my connection because of their delay,negative,miss connect delay
17,@AmericanAir helped me rebook my flight quickly,positive,americanair help rebook flight quickli
18,Cabin was clean and comfortable,positive,cabin clean comfort
19,"They refused to change my seat, very unhelpful",negative,refus chang seat unhelp
20,"Just an ordinary flight, everything was normal",neutral,ordinari flight everyth normal
21,Loved the new in-flight menu options,positive,love new inflight menu option
22,Baggage claim took forever,negative,baggag claim took forev
23,Polite crew but very noisy cabin,neutral,polit crew noisi cabin
24,@UnitedAirlines app kept crashing during check-in,negative,unitedairlin app kept crash checkin
25,"Had extra legroom and free snacks, amazing!",positive,extra legroom free snack amaz
26,Boarding was chaotic and disorganized,negative,board chaotic disorgan
27,Comfortable seats and great WiFi on board,positive,comfort seat great wifi board
28,Staff did their best despite the delay,neutral,staff best despit delay
29,Worst airline experience in years,negative,worst airlin experi year

In [232]:
#Step: 4
#a) Convert text to numerical vectors (TF-IDF)
# b) check x,y and shape len
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df['clean_tweet'])
y = df['sentiment']
print(x)
print(y)
print("Shape of x:", x.shape)      
print("Length of y:", len(y))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 140 stored elements and shape (30, 105)>
  Coords	Values
  (0, 98)	0.3804945349431948
  (0, 41)	0.2838360742053801
  (0, 26)	0.34767619843477227
  (0, 51)	0.4267493823409172
  (0, 103)	0.3804945349431948
  (0, 37)	0.3804945349431948
  (0, 34)	0.4267493823409172
  (1, 60)	0.3917559302157924
  (1, 85)	0.3917559302157924
  (1, 27)	0.4393797699957502
  (1, 24)	0.3917559302157924
  (1, 91)	0.3917559302157924
  (1, 44)	0.4393797699957502
  (2, 3)	0.4576898872817969
  (2, 59)	0.513328993622341
  (2, 61)	0.513328993622341
  (2, 30)	0.513328993622341
  (3, 86)	0.36253162556198376
  (3, 10)	0.33126262222553676
  (3, 72)	0.4066028104995579
  (3, 5)	0.4066028104995579
  (3, 48)	0.36253162556198376
  (3, 54)	0.4066028104995579
  (3, 88)	0.36253162556198376
  (4, 84)	0.4610552498655506
  :	:
  (24, 55)	0.41617114486261303
  (24, 99)	0.46676302208846976
  (24, 4)	0.46676302208846976
  (24, 23)	0.46676302208846976
  (25, 43)	0.42578964696644145
  (25, 87)	0.42578964696644145
  (25, 58)	0.42578964696644145
  (25, 38)	0.4775507981401452
  (25, 2)	0.4775507981401452
  (26, 10)	0.4991779343719709
  (26, 15)	0.6127076749299507
  (26, 31)	0.6127076749299507
  (27, 10)	0.41162419185084204
  (27, 48)	0.45047879652031525
  (27, 84)	0.41162419185084204
  (27, 20)	0.45047879652031525
  (27, 101)	0.5052412860579577
  (28, 26)	0.44662508308527504
  (28, 90)	0.44662508308527504
  (28, 9)	0.5482025493912548
  (28, 29)	0.5482025493912548
  (29, 103)	0.47057826013532666
  (29, 37)	0.47057826013532666
  (29, 0)	0.5277841425128352
  (29, 104)	0.5277841425128352
0     negative
1     positive
2     negative
3     positive
4      neutral
5     negative
6     positive
7      neutral
8     positive
9     negative
10    negative
11    positive
12    positive
13    negative
14     neutral
15    positive
16    negative
17    positive
18    positive
19    negative
20     neutral
21    positive
22    negative
23     neutral
24    negative
25    positive
26    negative
27    positive
28     neutral
29    negative
Name: sentiment, dtype: object
Shape of x: (30, 105)
Length of y: 30

In [233]:
# Step 5: Split into train and test sets
# 80% training and 20% testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [234]:
# Step:6 Train a Logistic Regression model
# a: Create Logistic Model
# b: Train Logistic Model
model=LogisticRegression(max_iter=200, class_weight='balanced')
model.fit(x_train,y_train)

LogisticRegression(class_weight='balanced', max_iter=200)

In [235]:
#Step 7:
# Evaluate accuracy and classification report
# a. predict Model
y_pred = model.predict(x_test)
     
# b. Precision, reacll, F1-Score for each sentiments
print(classification_report(y_test, y_pred, target_names=['negative', 'neutral', 'positive']))

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         1
     neutral       0.00      0.00      0.00         1
    positive       0.50      0.50      0.50         4

    accuracy                           0.33         6
   macro avg       0.17      0.17      0.17         6
weighted avg       0.33      0.33      0.33         6

C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Faridah\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [236]:
#Step 8: Predict sentiment for new example tweets

new_tweets = [
    "Flight delays and cancellations.",
    "Poor website usability or digital service problems.",
    "Great service and smooth boarding!"
]

clean_tweets = [clean_text(t) for t in new_tweets]
tfidf_new = vectorizer.transform(clean_tweets)
preds = model.predict(tfidf_new)

for twt, pred in zip(new_tweets, preds):
    print(f"{twt} ---> {pred}")

Flight delays and cancellations. ---> neutral
Poor website usability or digital service problems. ---> negative
Great service and smooth boarding! ---> positive